spring.jpa.hibernate.ddl-auto: none
server.error.include-message: always

spring.datasource:
  url: jdbc:mysql://localhost:3307/mcq-db
  username: user
  password: pwd

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: dev.agasen
  pathsToMatch: /**